version: '2.4'
services:
  elasticsearch:
    container_name: elasticsearch
    build: docker/elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch
    environment:
      - ES_JAVA_OPTS="-Xms256m -Xmx1024m"
      - discovery.type=single-node
      - xpack.security.enabled=false  # セキュリティ機能を無効化
    ports:
      - '9200:9200'
  kibana:
    container_name: kibana
    build: docker/kibana
    image: search-playground-kibana
    ports:
      - '5601:5601'
