version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    build: docker/elasticsearch
    image: search-playground-elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m 
      - discovery.type=single-node
      - xpack.security.enabled=false  # セキュリティ機能を無効化
    ports:
      - '9200:9200'
  kibana:
    container_name: kibana
    build: docker/kibana
    image: search-playground-kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - '5601:5601'
