version: '2.4'
services:
  elasticsearch:
    container_name: elasticsearch
    build: docker/elasticsearch
    image: search-playground-elasticsearch
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx750m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
      ENV_SERVER_LOCAL_IP: 127.0.0.1
    ports:
      - '9200:9200'
  kibana:
    container_name: kibana
    build: docker/kibana
    image: search-playground-kibana
    ports:
      - '5601:5601'
  cerebro:
    container_name: cerebro
    build: docker/cerebro
    image: search-playground-cerebro
    ports:
      - '9000:9000'
